name: "update ci image"
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    tags-ignore:
      - "**"
    paths:
      - ".devcontainer/**"
  schedule:
    - cron: "30 2 * * 3"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: build
        uses: devcontainers/ci@v0.2
        with:
          imageName: ghcr.io/${{ github.repository }}/devcontainers-ci
          runCmd: |
            echo done
